### ISSUE TITLE
Las imágenes no se posicionan correctamente en el pdf autogenerado

### ISSUE THREAD

**Issue by AlvaroMoreP** [AlvaroMoreP/go-bees#1]

**Comment by ABenGar** [comment]
http://stackoverflow.com/questions/24285445/sphinx-to-latex-figure-placement

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 20 Jan 2017
Fix images position #1

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 20 Jan 2017
Fix images position #1

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 20 Jan 2017
Fix images position #1

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 20 Jan 2017
Fix images position #1

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 20 Jan 2017
Fix images position #1

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 21 Jan 2017
Fix images position #1

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 21 Jan 2017
Fix images position #1

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 21 Jan 2017
Fix images position #1
