### ISSUE TITLE
Diseñar poster 

### ISSUE THREAD

**Issue by AlvaroMoreP** [AlvaroMoreP/go-bees#19]

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 14 Feb 2017

Add poster #19

**Comment by ABenGar** [comment]
https://raw.githubusercontent.com/davidmigloz/go-bees/master/docs/latex/cartel.jpg

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 16 Feb 2017
Update poster #19
