### ISSUE TITLE
Crear página web

### ISSUE THREAD

**Issue by AlvaroMoreP** [AlvaroMoreP/go-bees#20]
https://startbootstrap.com/template-overviews/new-age/
http://www.grabon.in/mobile-apps/

http://bronto.github.io/javasphinx/

**Comment by AlvaroMoreP** [comment]
http://gobees.io/

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 11 Feb 2017
Add Google Play link #20

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 11 Feb 2017
Update .gitignore #20

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 11 Feb 2017
Finish website #20
