### ISSUE TITLE
Grabar discos

### ISSUE THREAD

**Issue by AlvaroMoreP** [AlvaroMoreP/go-bees#23]
- Código fuente app
- Ejecutable app
- Herramientas
- Plataforma de desarrollo del algoritmo
- Herramienta de conteo de abejas
- Documentación
- Memoria
- Anexos
- JavaDoc
- Dataset de videos

**README**

- Repositorio GoBees
- Repositorio prototipos
- Repositorio dependencia OpenCV

**Comment by ABenGar** [comment]
davidmigloz added a commit that referenced this issue on 1 Feb 2017
Add cd cover #23

**Comment by ABenGar** [comment]
added a commit that referenced this issue on 1 Feb 2017
Add cd cover #23
